# Generated by Django 2.0 on 2018-11-07 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=11, verbose_name='年龄')),
                ('hobby', models.CharField(max_length=20, verbose_name='爱好')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.RemoveField(
            model_name='heroinfo',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookInfo',
        ),
        migrations.DeleteModel(
            name='HeroInfo',
        ),
    ]
